### PR TITLE
Extend errors in type Collection, update http2curl path

### PR DESCRIPTION
**Pull request by SchumacherFM**
http2curl moved to a new import path.
type Collection has two new fields which might contain errors.
Those fields are optional to check if some structure on contentful
backend side was incorrectly configured.

After merge please tag the new release.

### CODE REVIEW

**Comment by SchumacherFM** [comment]
@loeffert can you please review and merge this?

**Comment by SchumacherFM** [comment]
@loeffert can you please review and merge this?

**Comment by SchumacherFM** [comment]
any updates?

**Review by cvidmar — APPROVED** [review]
LGTM!

**Pull request merged**
